Algoritmo "Lista03Ex04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Aldo Henrique
// Descrição   : Gera números entre 1000 e 1999
// Autor(a)    : André José
// Data atual  : 18/03/2019
Var
   // Seção de Declarações das variáveis
   i: inteiro

inicio
   para i de 1000 ate 1999 faca
      se (i%11 = 5) entao
         escreval (i)
      fimse
   fimpara

Fimalgoritmo
