Algoritmo "Lista03Ex05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Aldo Henrique
// Descrição   : Soam dos números pares
// Autor(a)    : André José
// Data atual  : 18/03/2019
Var
   i, soma: inteiro

Inicio
      para i de 0 ate 10 passo 2 faca
      escreva(i)
      
      soma<-soma+i
      
      fimpara
      
      escreva(" O resultado da soma dos números pares é: ",soma)

Fimalgoritmo