Algoritmo "Lista03Ex02"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Aldo Henrique
// Descrição   : Exibir a tabuada de 0 a 9
// Autor(a)    : André José
// Data atual  : 18/03/2019
Var
   n, cont, m: inteiro

Inicio

   cont <- 0
   escreva("Digite número: ")
   leia(n)
   enquanto cont < 10 faca
      cont<- cont + 1
      m <- cont * n

      escreva (n, " x ", cont, " = ",m)
   fimenquanto

Fimalgoritmo